# Generated by Django 3.2.3 on 2021-09-06 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllofThem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='List.student')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='List.subject')),
                ('teachers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='List.teacher')),
            ],
        ),
    ]
