# Generated by Django 3.2.3 on 2021-09-06 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0002_allofthem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allofthem',
            old_name='students',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='allofthem',
            old_name='subjects',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='allofthem',
            old_name='teachers',
            new_name='teacher',
        ),
    ]
