# Generated by Django 3.2.3 on 2021-08-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0003_auto_20210906_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllofOutlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('outlay', models.IntegerField(default=0)),
                ('spending_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AllofThem',
        ),
    ]
