# Generated by Django 3.2.3 on 2021-09-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0004_auto_20210829_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='allofoutlay',
            name='for_teachers',
            field=models.BooleanField(default=False),
        ),
    ]
