# Generated by Django 3.2.3 on 2021-09-14 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0005_allofoutlay_for_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allofoutlay',
            name='for_teachers',
        ),
    ]
